language: cpp
 
#we are going to use containers
sudo: false

cache:
  ccache: true
  directories:
    - $HOME/.ccache

env:
  global:
    - USE_CCACHE=1
    - CCACHE_COMPRESS=1
    - CCACHE_MAXSIZE=200M
    - CCACHE_CPP2=1
    

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5
      env: 
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
      
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-precise-3.6          
            - ubuntu-toolchain-r-test
           packages:
            - clang-3.6  
       env:
          - MATRIX_EVAL="CC=clang-3.6 && CXX=clang++-3.6"

addons:
  apt:
    packages:
    - libegl1-mesa-dev
    - libgles2-mesa-dev  
    - libsdl2-dev
    - libcurl4-openssl-dev

  
before_install:
  - eval "${MATRIX_EVAL}"
  - cd yabause
  - mkdir build
  - cd build
  - export GIT_HASH=$(git rev-parse --short HEAD)
  
script:
 - cmake -DYAB_PORTS=glfw .. && cmake --build .

notifications:
  email: false

  
