language: cpp
sudo: false
cache:
  apt: true
env:
  global:
    - GLOBAL=1

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5
            - libegl1-mesa-dev
            - libgles2-mesa-dev  
            - libsdl2-dev
            - libcurl4-openssl-dev
    
      env:
       - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
        
    - os: linux
      addons:
        apt:
          sources: ['llvm-toolchain-trusty-3.6', 'ubuntu-toolchain-r-test']
          packages:
            - clang-3.6
            - libegl1-mesa-dev
            - libgles2-mesa-dev  
            - libsdl2-dev
            - libcurl4-openssl-dev
      env: 
        - MATRIX_EVAL="CC=clang-3.6 && CXX=clang-3.6"

    - android:
        components:
          - tools
          - platform-tools
          - build-tools-23.0.2
          - android-23
          - extra-google-m2repository
          - extra-android-m2repository
        before_install:
          - rm -fr $HOME/android-ndk-r16b
          - curl -L http://dl.google.com/android/repository/android-ndk-r16b-linux-x86_64.zip -O
          - unzip -oq android-ndk-r16b-linux-x86_64.zip
          - rm android-ndk-r16b-linux-x86_64.zip
          - export ANDROID_NDK_HOME=$HOME/android-ndk-r16b
          - cd yabause
          - mkdir build
          - cd build          
        script:
          - cmake -DCMAKE_TOOLCHAIN_FILE=../src/android/androidtoolchain.cmake -DANDROID_ABI="armeabi-v7a with NEON" -DANDROID_NATIVE_API_LEVEL=19 -DYAB_PORTS=android -DYAB_WANT_ARM7=TRUE -DYAB_WANT_C68K=FALSE -DYAB_WANT_DYNAREC_DEVMIYAX=TRUE
          - cmake --build .
          - cd ../src/android
          - ./gradlew assembleDebug
          
before_install:
  - eval "${MATRIX_EVAL}"
  - cd yabause
  - mkdir build
  - cd build
  - export GIT_HASH=$(git rev-parse --short HEAD)
  
script:
 - cmake -DYAB_PORTS=glfw .. && cmake --build .

notifications:
  email: false

  
