language: cpp

os:
  - linux

compiler:
  - clang
  - gcc

addons:
  apt:
    sources:
    - llvm-toolchain-precise-3.6
    - ubuntu-toolchain-r-test
    packages:
    - clang-3.6
    - gcc-5
    - g++-5
    - libegl1-mesa-dev
    - libgles2-mesa-dev  
    - libsdl2-dev
    - libcurl4-openssl-dev
  
before_install:
  # Prepare compiler
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.6" CC="clang-3.6"; fi
  # only build the first port if running a coverity scan. otherwise coverity will attempt to analyze all the builds
  - if ([[ "${TRAVIS_JOB_NUMBER##*.}" != "1" ]] && [[ "${TRAVIS_BRANCH}" == "coverity_scan" ]]); then false ; fi
  - cd yabause
  - mkdir build
  - cd build
  - export GIT_HASH=$(git rev-parse --short HEAD)
  
script:
 - cmake -DYAB_PORTS=glfw .. && cmake --build .

notifications:
  email: false

sudo: false

cache:
  - apt
  
